"""Quantum error-correction and magic-state distillation protocols."""

from .mek_magic_state_distillation import (
    MEKCircuitBuild,
    MEKBenchmarkPoint,
    H_STATE_ERROR_SITES,
    ket_H,
    ket_minus_H,
    rho_H_twirled,
    mek_acceptance_probability,
    mek_undetected_marginal_probability,
    mek_undetected_any_output_probability,
    mek_output_error_probability,
    mek_any_output_error_probability,
    mek_threshold,
    prepare_H_resource,
    inject_y_pi_over_4,
    apply_controlled_h_via_mek_injection,
    build_mek_10to2_scaffold_circuit,
    build_mek_10to2_paper_exact_circuit,
    build_mek_resource_noise,
    find_resource_prep_ops,
    compare_to_paper_formula,
    marginal_H_error_from_rho,
)

__all__ = [
    "MEKCircuitBuild",
    "MEKBenchmarkPoint",
    "H_STATE_ERROR_SITES",
    "ket_H",
    "ket_minus_H",
    "rho_H_twirled",
    "mek_acceptance_probability",
    "mek_undetected_marginal_probability",
    "mek_undetected_any_output_probability",
    "mek_output_error_probability",
    "mek_any_output_error_probability",
    "mek_threshold",
    "prepare_H_resource",
    "inject_y_pi_over_4",
    "apply_controlled_h_via_mek_injection",
    "build_mek_10to2_scaffold_circuit",
    "build_mek_10to2_paper_exact_circuit",
    "build_mek_resource_noise",
    "find_resource_prep_ops",
    "compare_to_paper_formula",
    "marginal_H_error_from_rho",
]
